### ISSUE TITLE
As a school leader I would like to register an expression of interest for using the tool in my school so that CybersafeIreland can log that and get back to me with a survey link and school Id.

### ISSUE THREAD

**Issue by bethanyios** [cybersafe-dev/cybersafety-tool#21]
Form is there but needs to be connected to salesforce

**Comment by jc2820** [comment]
The flow has changed so that school admins can log in to the admin app directly from the mini-site. As such we don't need the expression of interest form, and salesforce data will be added directly from the signup form.
