### ISSUE TITLE
Gatsby and plugins becoming outdated

### ISSUE THREAD

**Issue by jc2820** [cybersafe-dev/cybersafety-tool#311]
Gatsby is currently v2.x.x and should be upgraded gradually through v3-latest to v4-latest including all gatsby prefixed plugins.
The challenge is that from v2-3 gatsby switches to webpack 5 (from current usage 4). This requires specific attention as there are many breaking changes that will take attention to fix.

Updating react-pdf to latest working version could mitigate some stress as it seems to have (currently) the most dependency on webpack 4.

This is recommended as it is becoming difficult to manage module vulnerabilities without breaking changes due to use of  gatsby v2.

**Comment by cybersafe-dev** [comment]
Sorted to give Yalla a better start on the tool than this would have been!
